//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidingInfo
    {
        public int Id { get; set; }
        public Nullable<int> BidderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> BidDateTime { get; set; }
        public Nullable<double> BiddingMoney { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual Product Product { get; set; }
    }
}
