//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bid_MVC_DBEntities : DbContext
    {
        public Bid_MVC_DBEntities()
            : base("name=Bid_MVC_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BidingInfo> BidingInfoes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SoldInfo> SoldInfoes { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    }
}
