//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.BidingInfoes = new HashSet<BidingInfo>();
            this.SoldInfoes = new HashSet<SoldInfo>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string Category { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<int> SellerId { get; set; }
        public Nullable<double> MinimumBid { get; set; }
    
        public virtual ICollection<BidingInfo> BidingInfoes { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<SoldInfo> SoldInfoes { get; set; }
    }
}
