//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.BidingInfoes = new HashSet<BidingInfo>();
            this.Products = new HashSet<Product>();
            this.SoldInfoes = new HashSet<SoldInfo>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public bool Facebook { get; set; }
        public bool Google { get; set; }
        public bool Twitter { get; set; }
    
        public virtual ICollection<BidingInfo> BidingInfoes { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<SoldInfo> SoldInfoes { get; set; }
    }
}
